const professiondata = () => {
    const data = [
        { "name": "Physician Assistants (PAs)" },
    { "name": "Nurse Practitioners (NPs)" },
    { "name": "Pharmacists" },
    { "name": "Dentists" },
    { "name": "Optometrists" },
    { "name": "Podiatrists" },
    { "name": "Chiropractors" },
    { "name": "Physical Therapists (PTs)" },
    { "name": "Occupational Therapists (OTs)" },
    { "name": "Speech-Language Pathologists" },
    { "name": "Radiologic Technologists" },
    { "name": "Medical Laboratory Technicians" },
    { "name": "Respiratory Therapists" },
    { "name": "Dietitians/Nutritionists" },
    { "name": "Paramedics and Emergency Medical Technicians (EMTs)" },
    { "name": "Medical Social Workers" },
    { "name": "Audiologists" },
    { "name": "Anesthetists (CRNAs)" },
    { "name": "Surgical Technologists" },
    { "name": "Health Information Technicians" },
    { "name": "Genetic Counselors" },
    { "name": "Orthotists and Prosthetists" },
    { "name": "Clinical Psychologists" },
    { "name": "Mental Health Counselors" },
    { "name": "Home Health Aides" },
    { "name": "Medical Assistants" },
    { "name": "Cardiovascular Technologists" },
    { "name": "Clinical Laboratory Scientists" },
    { "name": "Cytotechnologists" },
    { "name": "Diagnostic Medical Sonographers" },
    { "name": "Endoscopy Technicians" },
    { "name": "Forensic Nurses" },
    { "name": "Geriatric Care Managers" },
    { "name": "Health Educators" },
    { "name": "Infection Control Practitioners" },
    { "name": "Medical Coders" },
    { "name": "Midwives" },
    { "name": "Neonatal Nurses" },
    { "name": "Nuclear Medicine Technologists" },
    { "name": "Oncology Nurses" },
    { "name": "Orthopedic Technologists" },
    { "name": "Pain Management Nurses" },
    { "name": "Palliative Care Nurses" },
    { "name": "Patient Advocates" },
    { "name": "Perioperative Nurses" },
    { "name": "Phlebotomists" },
    { "name": "Public Health Nurses" },
    { "name": "Rehabilitation Counselors" },
    { "name": "Sleep Technologists" },
    { "name": "Sports Medicine Physicians" },
    { "name": "Telehealth Nurses" },
    { "name": "Transplant Coordinators" },
    { "name": "Trauma Nurses" },
    { "name": "Urology Nurses" },
    { "name": "Veterinary Technicians" },
    { "name": "Wound Care Specialists" }
      ];
  
    return data;
  };
  
  export default professiondata;